### ISSUE TITLE
Blank page after Login after database backup & restore

### ISSUE THREAD

**Issue by nfsecurity** [KETSE/casebox#31]
Hello Casebox Team:

I was testing my backup & restore procedure with Casebox in my Linux system. First, I did a database removal (drop database cb__casebox and cd_nfsec) and then I did a mysql procedure to upload the dumped databases. All occurred normally, I did this type of procedures before with another sites.

Next to the restore, I tried to login in my Casebox and surprise: I had a blank page after the login process (I have two step verification enabled).

No error log under the logs directory files. The only logs that I have are the query.log file from MariaDB and the ssl_access:

127.0.0.1 - - [13/Dec/2015:07:32:16 +0100] "POST /nfsec/login/auth/ HTTP/1.1" 500 -

151213  7:13:24	   42 Connect	cb@localhost as anonymous on 
		   42 Query	SET NAMES utf8
		   42 Query	SET @@session.time_zone = "+00:00"
		   42 Query	SELECT id
                FROM `cb__casebox`.`cores` WHERE name = 'nfsec'
		   42 Query	SELECT *
            FROM `cb__casebox`.`cores`
            WHERE id = '9'
		   42 Query	USE `cb_nfsec`
		   42 Query	SET NAMES utf8
		   42 Query	SET @@session.time_zone = "+00:00"
		   42 Query	SELECT *
                FROM `cb__casebox`.`config`
		   42 Query	SELECT id
                FROM `cb__casebox`.`cores` WHERE name = 'nfsec'
		   42 Query	SELECT *
            FROM `cb__casebox`.`cores`
            WHERE id = '9'
		   42 Query	SELECT *
            FROM config
            ORDER BY pid, `order`
		   42 Query	SELECT id
            FROM templates
            WHERE `type` = 'shortcut'
            ORDER BY id
		   42 Query	SELECT *
            FROM sessions
            WHERE id = 'h7k6ddq8r560a767fdpq2nlhj2'
                AND (
                    (expires > CURRENT_TIMESTAMP)
                    OR (expires IS NULL)
                )
		   42 Query	SELECT name, en
        FROM cb__casebox.translations
        WHERE `type` < 2
		   42 Query	SELECT *
        FROM translations
        WHERE `type` < 2
		   42 Query	CALL p_user_login('root', 'XXXXXXXXXX', '|127.0.0.1|')
		   42 Query	UPDATE sessions
            SET expires = TIMESTAMPADD(SECOND, 3, CURRENT_TIMESTAMP)
            WHERE (
                (id = 'h7k6ddq8r560a767fdpq2nlhj2') OR
                (pid = 'h7k6ddq8r560a767fdpq2nlhj2')
                ) and id <> 'h7k6ddq8r560a767fdpq2nlhj2'
		   42 Query	INSERT INTO sessions
            (id, pid, expires, user_id, data)
            VALUES('h7k6ddq8r560a767fdpq2nlhj2', 'h7k6ddq8r560a767fdpq2nlhj2', TIMESTAMPADD(SECOND, '259200', CURRENT_TIMESTAMP), '0', '')
            ON DUPLICATE KEY UPDATE
                expires = TIMESTAMPADD(SECOND, '259200', CURRENT_TIMESTAMP)
                ,last_action = CURRENT_TIMESTAMP
                ,user_id = '0'
                ,data = ''
		   42 Query	DELETE
            FROM sessions
            WHERE (expires < CURRENT_TIMESTAMP)
                OR (last_action < TIMESTAMPADD( DAY, -3, CURRENT_TIMESTAMP))
		   42 Quit	

I'm lost :( Can you help me ?, thank you so much.

**Comment by nfsecurity** [comment]
I just change in php.ini display_errors = Off to On and then the browser is showing:

Fatal error: Uncaught exception 'Exception' with message 'Query error (cb_nfsec)' in /var/www/casebox/httpsdocs/lib/DB.php:203 Stack trace: #0 /var/www/casebox/httpsdocs/classes/CB/DataModel/Users.php(258): CB\DB\dbQueryError() #1 /var/www/casebox/httpsdocs/classes/CB/User.php(25): CB\DataModel\Users::auth('root', 'XXXXXXX', '|127.0.0.1|') #2 /var/www/casebox/httpsdocs/auth.php(63): CB\User::login('root', 'XXXXXXX') #3 /var/www/casebox/httpsdocs/index.php(32): include('/var/www/casebo...') #4 {main} thrown in /var/www/casebox/httpsdocs/lib/DB.php on line 203

Any idea ?

**Comment by nfsecurity** [comment]
I solve the problem myself: missing functions and procedures from Casebox dump databases in my backup procedure :(
